### ISSUE TITLE
ShopifySDK object uses static variables for config

### ISSUE THREAD

**Issue by shawnhind** [phpclassic/php-shopify#72] opened 2019-03-07 22:11 UTC
When developing certain apps it isn't unreasonable to expect that you might be needing to process API calls to a list of stores.

So for example in my system I have a Shop model which contains a bunch of methods that can be performed on the store and utilizes an internal ShopifySDK object to perform those operations.

The ShopifySDK object uses static properties for the configs rather than object properties meaning that an array of my Shop model objects all have an API client going to the last set store.

**Comment by shawnhind** [comment] 2019-03-07 22:12
Realized after submitting that this is the same as issue #61.

I'm fixing this "bug" (design decision?) on my fork of the repo and will submit a pull request if interested.

**Comment by tareqtms** [comment] 2019-03-08 03:02
@shawnhind 
The change you made is not backward compatible (other codes using the same function will fail without update). So cannot be merged to the current version. We are not going to create a major release soon, so please create a pull request with changes that will not break anything.

**Comment by tareqtms** [comment] 2019-05-22 14:46
Duplicate of #61

**Closed by tareqtms** 2019-05-22 14:46 UTC
